name = "Blockparty Wednesday"
author = "Serene_Sparks_+rznant"
version = "0.6.15-rc1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09fd4bcefea3131a9a82920d0025ae55d7c0d57d23e5b9df01ce1d3e900773ac"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
