name = "Blockparty Wednesday"
author = "Serene_Sparks_+rznant"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7677631fc12c776afcb972d5da83a9146b67654ce533e647a19446dcf9d5bd3c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
