name = "Blockparty Wednesday"
author = "Serene_Sparks_+rznant"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "736efc7db4db54bb9deff1a4f7a1eeeb4b18b91b7a6883e0deb3f41282e5f89e"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
