name = "Blockparty Wednesday"
author = "Serene_Sparks_+rznant"
version = "0.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b8e84f86f6fcd76174362c540d949e5cac4db2e05e70472fc684e6635f84495"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
