name = "Blockparty Wednesday"
author = "Serene_Sparks_+rznant"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5f7e06cdff2c853cdf576dfaae0b40527370ed81b098475f8160772d9d4168a"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
