name = "Blockparty Wednesday"
author = "Serene_Sparks_+rznant"
version = "0.6.15-rc1a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc7d5211945a88a9c92167e7d48de1a512596b7824eff3be8c71efae95eaadac"

[versions]
forge = "51.0.30"
minecraft = "1.20.1"
