name = "Blockparty Wednesday"
author = "Serene_Sparks_+rznant"
version = "0.6.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ac1140ce3d39250590f6de99d8151591be9d19cd8171a2040c5bf109ad20718"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
