name = "Blockparty Wednesday"
author = "Serene_Sparks_+rznant"
version = "0.6.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "162b1b59a1bb2afcdfd3cfc20a86f2040bdb31cafc3babb5cb2a8c23a05c333b"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
