name = "Blockparty Wednesday"
author = "Serene_Sparks_+rznant"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2dcd19b76bcf0e6f0880212d6c3e0671704674c22fc3980b7cf78f17f6b9ea36"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
