name = "Blockparty Wednesday"
author = "Serene_Sparks_+rznant"
version = "0.6.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "786fdc76977d4e854f8c24c7e05b9f7f0bb30b373c692e03de7b34c547ea01cf"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
