name = "Blockparty Wednesday"
author = "Serene_Sparks_+rznant"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5532bb3a68fbdd9f82d49fcea158f4aa8ca1d159f072b9360cee9ca94d5f1eb"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
