name = "Blockparty Wednesday"
author = "Serene_Sparks_+rznant"
version = "0.6.7b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f67445660ec4fb9ab839a8690c8898f23d5040c2be7d4452a0b0948b6c04c5cd"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
