name = "Blockparty Wednesday"
author = "Serene_Sparks_+rznant"
version = "0.6.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "138f5660e3afa2aa678836f7efea704b867ef841bb92ae3e6b5d9c66fd3a3a6a"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
