name = "Blockparty Wednesday"
author = "Serene_Sparks_+rznant"
version = "0.6.7c"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "923c8db0dbe55392055984a81fd2cdc66d22553c604a144a44b2b33173564b79"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
