name = "Blockparty Wednesday"
author = "Serene_Sparks_+rznant"
version = "0.6.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2515e2da87748f15e6c344f23c229a690d586975e5dccbc4666eefb685dc8a6"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
