name = "Blockparty Wednesday"
author = "Serene_Sparks_+rznant"
version = "0.6.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf80def802373d670043ae64af915f975e472ffc6b9ff88e49f38f0bdcbd5071"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
