name = "Blockparty Wednesday"
author = "Serene_Sparks_+rznant"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85a52658fce76718b81917edfc28b0e4f664218440143e5eda57b2682fcde657"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
