name = "Blockparty Wednesday"
author = "Serene_Sparks_+rznant"
version = "0.6.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1a4bf1e4828791b89ba6dc2050f13495328467b3f20711a6171472c6ff251de"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
