name = "Blockparty Wednesday"
author = "Serene_Sparks_+rznant"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbf9e24cc832d561d0beac29bdcd64ad7b33029b672c0c5cdc0aa614153c66e2"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
