name = "Blockparty Wednesday"
author = "Serene_Sparks_+rznant"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a83a87adcba874dcd7158c51736821c0fc9f17ae7ed3b10393164777ca6aa19a"

[versions]
minecraft = "1.20.1"
quilt = "0.26.1-beta.1"
