name = "Blockparty Wednesday"
author = "Serene_Sparks_+rznant"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5219f08d52a47cd497762ace864427e31d780e63fbaf3dcab42e652758fc774f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
