name = "Blockparty Wednesday"
author = "Serene_Sparks_+rznant"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4dfa08f4da901b1f7cb3220d4d2eb7f546e27a4bc492b9943c031426e126161"

[versions]
minecraft = "1.20.1"
quilt = "0.26.1-beta.1"
